### ISSUE TITLE
作为api使用，访问http://127.0.0.1:3456/v1/chat/completions报错404

### ISSUE THREAD

**Issue by AwesomeDong** [missuo/FreeDuckDuckGo#9]

**Comment by missuo** [comment]
I hope you have the knowledge of the difference between POST/GET requests before using this project. Otherwise, I think you may not be suitable for using this project.

**Comment by AwesomeDong** [comment]
![image](https://github.com/missuo/FreeDuckDuckGo/assets/48645913/b3393651-e267-4a29-9eb7-71a41526276f)

**Comment by missuo** [comment]
> 作为api使用，访问http://127.0.0.1:3456/v1/chat/completions**报错404**

Obviously, I don't see any "404" characters appearing in your screenshot. Also, if the way you raise an issue is just a screenshot, then I may block you because you waste my time.

I can't know what your request parameters are just from a screenshot. I'm not a fortune teller.

**Comment by missuo** [comment]
> 作为api使用，访问 http://127.0.0.1:3456/v1/chat/completions **报错404**

Obviously, I don't see any "404" characters appearing in your screenshot. Also, if the way you raise an issue is just a screenshot, then I may block you because you waste my time.

I can't know what your request parameters are just from a screenshot. I'm not a fortune teller.

**Comment by AwesomeDong** [comment]
谢谢提醒，文字描述没写过来，我只是用它测试了oneapi，启动后我看到docker的后台是返回的500，可能是我操作不对，但我只是单纯想问一下，毫无恶意，鉴于你傲慢的行径，我完全可以去用别人的，祝好
![image](https://github.com/missuo/FreeDuckDuckGo/assets/48645913/a6d44258-4dd9-4275-a7ad-92b149ff3a07)

**Comment by missuo** [comment]
I believe this is not your first time using GitHub. I am happy to help anyone solve problems, but before raising an issue, you need to ensure two things: **first, make sure the problem really exists, and second, make sure you describe the problem clearly**.

However, you have not done either of these two things. In the title of this issue, you mentioned a 404 error. Obviously, you directly requested this link using a browser, but you may not know that the browser's request is a GET request, and this API does not support GET requests.

Later, you posted a screenshot showing a 500 Status Code, which I believe is the error returned during the testing of the One API you mentioned.

In summary, you clarified the problem through three submissions. From the first time you posted this issue to the last time you described it clearly, it took about 25 minutes. This is our communication cost. In my opinion, these 25 minutes are very important to me because I need to wait for your reply each time to further locate the problem. Besides, 25 minutes may not mean much to you. But please remember, I am not maintaining just one project, and the issues I need to reply to are not just one. This is an open-source project, and I do not charge you any fees. You are simply enjoying the fruits of my labor for free.

I think if one day you have the opportunity to maintain an open-source project, you will understand what I am saying today. Of course, you can choose to use other people's projects; that is your freedom. I just hope you can use the GitHub platform well. @AwesomeDong

**Comment by AwesomeDong** [comment]
好的，谢谢，确实抱歉，这里确实有我的问题，在描述上确实不对，不管怎么样，祝你顺利，哈哈哈，不过你真的让我觉得很可笑。希望你不会被这些东西压垮自己。保持开心最重要。

**Comment by missuo** [comment]
> 好的，谢谢，确实抱歉，这里确实有我的问题，在描述上确实不对，不管怎么样，祝你顺利，哈哈哈，不过你真的让我觉得很可笑。希望你不会被这些东西压垮自己。保持开心最重要。

Come on, aufer!

**Comment by sjlleo** [comment]
> 好的，谢谢，确实抱歉，这里确实有我的问题，在描述上确实不对，不管怎么样，祝你顺利，哈哈哈，不过你真的让我觉得很可笑。希望你不会被这些东西压垮自己。保持开心最重要。

提issue的目的就是遇到了问题然后解决问题嘛，这无可厚非，但是您可能没有读过《提问的智慧*》，阅读那个指南应该会有所帮助

开源作者都是用爱发电，若是想把商业软件那一套技术支持的态度照搬到这里可是完全没有用的哦

* https://zhuanlan.zhihu.com/p/664680014

**Comment by AwesomeDong** [comment]
> > 好的，谢谢，确实抱歉，这里确实有我的问题，在描述上确实不对，不管怎么样，祝你顺利，哈哈哈，不过你真的让我觉得很可笑。希望你不会被这些东西压垮自己。保持开心最重要。
> 
> 提issue的目的就是遇到了问题然后解决问题嘛，这无可厚非，但是您可能没有读过《提问的智慧*》，阅读那个指南应该会有所帮助
> 
> 开源作者都是用爱发电，若是想把商业软件那一套技术支持的态度照搬到这里可是完全没有用的哦
> 
> * https://zhuanlan.zhihu.com/p/664680014

不好意思，这是我第一次提问，我甚至都没想得到回复，我或许更适合在社区提问，你们执着的做法让我吃惊，而且我已经承认了我的问题，是时候结束这个话题了
